"""
One-time generator for frontend/js/world-map-data.js (offline world map outlines).

Run on an internet-connected machine only when the map needs regenerating:
    python scripts/build_world_map.py

Source: Natural Earth 110m countries (public domain) via the world-atlas package.
Projection must match AnalyticsModule.project() in frontend/js/analytics.js.
"""
import json
import os
import urllib.request

SRC = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "frontend", "js", "world-map-data.js")

# Equirectangular, cropped to exclude Antarctica
W, H = 1000, 440
LAT_TOP, LAT_BOTTOM = 84.0, -58.0


def project(lon, lat):
    x = (lon + 180.0) / 360.0 * W
    y = (LAT_TOP - lat) / (LAT_TOP - LAT_BOTTOM) * H
    return x, y


def decode_arcs(topo):
    sx, sy = topo["transform"]["scale"]
    tx, ty = topo["transform"]["translate"]
    arcs = []
    for arc in topo["arcs"]:
        x = y = 0
        pts = []
        for dx, dy in arc:
            x += dx
            y += dy
            pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)
    return arcs


def ring_coords(ring, arcs):
    coords = []
    for idx in ring:
        pts = arcs[idx] if idx >= 0 else list(reversed(arcs[~idx]))
        coords.extend(pts if not coords else pts[1:])
    return coords


def unwrap(coords):
    """Make longitudes continuous so rings crossing the antimeridian (Russia, Fiji)
    don't draw a line across the whole map. Returns one or two copies of the ring;
    the SVG viewBox clips whatever falls outside -180..180."""
    out = [coords[0]]
    for lon, lat in coords[1:]:
        prev = out[-1][0]
        while lon - prev > 180:
            lon -= 360
        while lon - prev < -180:
            lon += 360
        out.append((lon, lat))
    rings = [out]
    if max(p[0] for p in out) > 180:
        rings.append([(lon - 360, lat) for lon, lat in out])
    if min(p[0] for p in out) < -180:
        rings.append([(lon + 360, lat) for lon, lat in out])
    return rings


def ring_to_path(coords):
    parts = []
    prev = None
    for lon, lat in coords:
        x, y = project(lon, lat)
        pt = (round(x, 1), round(y, 1))
        if pt == prev:
            continue
        parts.append(f"{pt[0]:g} {pt[1]:g}")
        prev = pt
    if len(parts) < 3:
        return ""
    # Skip rings that are entirely below the crop line
    return "M" + "L".join(parts) + "Z"


def main():
    with urllib.request.urlopen(SRC, timeout=60) as r:
        topo = json.load(r)
    arcs = decode_arcs(topo)
    countries = []
    for geom in topo["objects"]["countries"]["geometries"]:
        polys = []
        if geom["type"] == "Polygon":
            polys = [geom["arcs"]]
        elif geom["type"] == "MultiPolygon":
            polys = geom["arcs"]
        d = ""
        for poly in polys:
            for ring in poly:
                for part in unwrap(ring_coords(ring, arcs)):
                    d += ring_to_path(part)
        name = (geom.get("properties") or {}).get("name", "")
        if d and name != "Antarctica":
            countries.append({"n": name, "d": d})

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* Generated by scripts/build_world_map.py - Natural Earth 110m (public domain). Do not edit. */\n")
        f.write(f"window.WORLD_MAP = {{ width: {W}, height: {H}, latTop: {LAT_TOP}, latBottom: {LAT_BOTTOM}, countries: ")
        f.write(json.dumps(countries, separators=(",", ":")))
        f.write(" };\n")
    print(f"Wrote {OUT} ({len(countries)} countries, {os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
